services:
  mongo:
    image: mongo:7.0
    container_name: radar-combustivel-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: radar_combustivel
    volumes:
      - mongo_radar_data:/data/db

volumes:
  mongo_radar_data:
